name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - uses: actions/setup-node@v4
    #   with:
    #     node-version: 18
    #     cache: 'npm'
    - name: Setup Node.js with PNPM
      uses: actions/setup-node@v3
      with:
        node-version: 18
        package-manager: pnpm
        
    - name: Install Dependencies
      run: pnpm install
    - name: Check PNPM version
      run: pnpm --version

    - name: Install TypeScript
      run: pnpm install --save-dev typescript

    - name: Build TypeScript
      run: npx tsc

    - name: Build the Docker image
      run: sh build.sh --buildImage web-server master